GET http://localhost:8080/api/v1/posts/5
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIwMDFAaW5mb3RyYWNrLmNvbS5hdSIsImV4cCI6MTc0NjAzNDU0MiwidXNlcklkIjoxfQ.6dT9VdbsoXlLIwzJRYfiZZ2V-XGay5GuT68VALZ_cG0