// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: internal/handler/proto/user/user_service.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      *string                `protobuf:"bytes,1,req,name=user_name,json=userName" json:"user_name,omitempty"`
	Password      *string                `protobuf:"bytes,2,req,name=password" json:"password,omitempty"`
	DisplayName   *string                `protobuf:"bytes,3,req,name=display_name,json=displayName" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignupRequest) Reset() {
	*x = SignupRequest{}
	mi := &file_internal_handler_proto_user_user_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupRequest) ProtoMessage() {}

func (x *SignupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_handler_proto_user_user_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupRequest.ProtoReflect.Descriptor instead.
func (*SignupRequest) Descriptor() ([]byte, []int) {
	return file_internal_handler_proto_user_user_service_proto_rawDescGZIP(), []int{0}
}

func (x *SignupRequest) GetUserName() string {
	if x != nil && x.UserName != nil {
		return *x.UserName
	}
	return ""
}

func (x *SignupRequest) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *SignupRequest) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

type SignupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      *string                `protobuf:"bytes,1,req,name=user_name,json=userName" json:"user_name,omitempty"`
	DisplayName   *string                `protobuf:"bytes,2,req,name=display_name,json=displayName" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignupResponse) Reset() {
	*x = SignupResponse{}
	mi := &file_internal_handler_proto_user_user_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupResponse) ProtoMessage() {}

func (x *SignupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_handler_proto_user_user_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupResponse.ProtoReflect.Descriptor instead.
func (*SignupResponse) Descriptor() ([]byte, []int) {
	return file_internal_handler_proto_user_user_service_proto_rawDescGZIP(), []int{1}
}

func (x *SignupResponse) GetUserName() string {
	if x != nil && x.UserName != nil {
		return *x.UserName
	}
	return ""
}

func (x *SignupResponse) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

var File_internal_handler_proto_user_user_service_proto protoreflect.FileDescriptor

const file_internal_handler_proto_user_user_service_proto_rawDesc = "" +
	"\n" +
	".internal/handler/proto/user/user_service.proto\x12\x04user\"k\n" +
	"\rSignupRequest\x12\x1b\n" +
	"\tuser_name\x18\x01 \x02(\tR\buserName\x12\x1a\n" +
	"\bpassword\x18\x02 \x02(\tR\bpassword\x12!\n" +
	"\fdisplay_name\x18\x03 \x02(\tR\vdisplayName\"P\n" +
	"\x0eSignupResponse\x12\x1b\n" +
	"\tuser_name\x18\x01 \x02(\tR\buserName\x12!\n" +
	"\fdisplay_name\x18\x02 \x02(\tR\vdisplayName2D\n" +
	"\vUserService\x125\n" +
	"\x06Signup\x12\x13.user.SignupRequest\x1a\x14.user.SignupResponse\"\x00B-Z+ep.k14/newsfeed/internal/handler/proto/user"

var (
	file_internal_handler_proto_user_user_service_proto_rawDescOnce sync.Once
	file_internal_handler_proto_user_user_service_proto_rawDescData []byte
)

func file_internal_handler_proto_user_user_service_proto_rawDescGZIP() []byte {
	file_internal_handler_proto_user_user_service_proto_rawDescOnce.Do(func() {
		file_internal_handler_proto_user_user_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_handler_proto_user_user_service_proto_rawDesc), len(file_internal_handler_proto_user_user_service_proto_rawDesc)))
	})
	return file_internal_handler_proto_user_user_service_proto_rawDescData
}

var file_internal_handler_proto_user_user_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_handler_proto_user_user_service_proto_goTypes = []any{
	(*SignupRequest)(nil),  // 0: user.SignupRequest
	(*SignupResponse)(nil), // 1: user.SignupResponse
}
var file_internal_handler_proto_user_user_service_proto_depIdxs = []int32{
	0, // 0: user.UserService.Signup:input_type -> user.SignupRequest
	1, // 1: user.UserService.Signup:output_type -> user.SignupResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_handler_proto_user_user_service_proto_init() }
func file_internal_handler_proto_user_user_service_proto_init() {
	if File_internal_handler_proto_user_user_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_handler_proto_user_user_service_proto_rawDesc), len(file_internal_handler_proto_user_user_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_handler_proto_user_user_service_proto_goTypes,
		DependencyIndexes: file_internal_handler_proto_user_user_service_proto_depIdxs,
		MessageInfos:      file_internal_handler_proto_user_user_service_proto_msgTypes,
	}.Build()
	File_internal_handler_proto_user_user_service_proto = out.File
	file_internal_handler_proto_user_user_service_proto_goTypes = nil
	file_internal_handler_proto_user_user_service_proto_depIdxs = nil
}
