GET http://localhost:8080/api/v1/users/profile/5
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIwMDVAaW5mb3RyYWNrLmNvbS5hdSIsImV4cCI6MTc0NjAzMjc1MCwidXNlcklkIjowfQ._wg4a9nxk9U5sShgqOepwy1imZgcyvt-KXiapFCvtkU